[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."sync"]
  schedule = "0 * * * *"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
